### ISSUE TITLE
SO3 squared distance is not symmetric in edge cases

### ISSUE THREAD

**Issue by ninamiolane** [ninamiolane/geomstats#12]
The original problem is the non-symmetry of the canonical riemannian squared distance on SO(3), in some edge cases:
```
SO3 = SpecialOrthogonalGroup(n=3)
metric = SO3.bi_invariant_metric
point_1 =  (np.pi - 1e-9) / np.sqrt(2) * np.array([0., 1., -1])  
# = [ 0.        ,  2.22144147, -2.22144147]
point_2 =  (np.pi + 0.3) / np.sqrt(5) * np.array([-2., 1., 0])  
# = [-3.07825405,  1.53912702,  0.        ]

sq_dist_1_2 = metric.squared_dist(point_1, point_2)
sq_dist_2_1 = metric.squared_dist(point_2, point_1)
```
gives
```
squared distance from 1 to 2: 2.3231752211574856
squared distance from 2 to 1: 3.4963809233705936
```

This problem probably has an origin in / is linked to the fact that group_log and group_exp, as well as metric.log and metric.exp, are not inverse of each other in some edge cases. (observed experimentally).

And this, in turn, probably has an origin in the inheritance of the function regularize from the class LieGroup (the function regularize is just the identity) to the class SpecialOrthogonalGroup (the regularization of the rotation vector as we know it).

Also, there might be more than one problem.

**Comment by farrell236** [comment]
The issue could be elsewhere other than edge cases, currently I'm testing with these parameters and they don't pass the symmetry test:

`
point_1 = np.array([0.16329, -0.660283, 2.75099])
point_2 = np.array([-1.2297, 0.551821, -0.370994])

sq_dist_1_2 = metric.squared_dist(point_1, point_2) # gives 6.21791107188
sq_dist_2_1 = metric.squared_dist(point_2, point_1) # gives 8.21602384143
`

**Comment by farrell236** [comment]
The bug i think is due to the signage of the vector not being tracked. 

For example; if you have a vector V with a norm of 3.5pi, after passing it through regularize(), we would have -V with norm of 0.5pi. This is correct as +1.5pi of V and -0.5pi of -V is the same rotation. However, in other different functions, this sign is not tracked as np.linalg.norm() always provides a +ve value, functions e.g. matrix_from_rotation_vector() or jacobian_translation() have angle = np.linalg.norm(rot_vec) assumes only the positive value without taking signage into consideration. Therefore the angle used is 0.5pi as opposed to -0.5pi or 1.5pi.

Using the following points:
```
point_1 = np.array([0.16329, -0.660283, 2.75099])
point_2 = np.array([-1.2297, 0.551821, -0.370994])
```

and running the following function:
```
sq_dist_1_2 = metric.squared_dist(point_1, point_2)
```

Following the stack trace squared_dist() -> log(), [this multiplication](https://github.com/ninamiolane/geomstats/blob/4590a223f19fa3851a98e70abeeb9f937e3d1531/geomstats/special_orthogonal_group.py#L197) would return:

```
[ 2.41953917 -1.34148147  1.90695527]
```

Which the norm is `3.3600923694592719`, the regularisation function would make this vector have a norm of `3.3600923694592719 - pi` and flip the vector (times -1). The sign of this vector is not tracked.

This vector is then used in squared_norm(), the following stack trace is as follows:
```
riemannian_metric.py (RiemannianMetric): squared_norm()
riemannian_metric.py (RiemannianMetric): inner_product()
invariant_metric.py (InvariantMetric): inner_product_matrix()
special_orthogonal_group.py (SpecialOrthogonalGroup): regularize()
special_orthogonal_group.py (SpecialOrthogonalGroup): belongs()
special_orthogonal_group.py (SpecialOrthogonalGroup): **jacobian_translation()**
special_orthogonal_group.py (SpecialOrthogonalGroup): belongs()
special_orthogonal_group.py (SpecialOrthogonalGroup): regularize()
special_orthogonal_group.py (SpecialOrthogonalGroup): belongs()
special_orthogonal_group.py (STATIC): skew_matrix_from_vector()
```

The problem here then rises in jacobian_translation(), [specifically here](https://github.com/ninamiolane/geomstats/blob/4590a223f19fa3851a98e70abeeb9f937e3d1531/geomstats/special_orthogonal_group.py#L435). The angle used here is `3.3600923694592719 - pi` but the sign is not taken into consideration. This causes the angle here should be `3.3600923694592719` and not `3.3600923694592719 - pi` due to the vector being flipped from before.

Is this the bug we were looking for?

**Comment by ninamiolane** [comment]
Yes !! You tracked the issue in a very systematic way, well done! :-D 

Here's what was happening on the math side: I was regularizing the points and the tangent vectors, ...whereas only the points need regularization. 

The points need regularization because we want a unique representation for each point. If we think about the rotations as points on a sphere, each rotation should map to one and only one point on the sphere. 

The tangent vectors, however, don't need regularization. We can also think of them as tangent vectors of the sphere: even if a tangent vector has a norm that is above 2*pi, there is nothing that prevent us from shooting along it and looping several times around the sphere before reaching a point on the sphere.

I will fix this everywhere and push the code. Thanks again!

**Comment by farrell236** [comment]
thanks, glad to have finally tracked it down :D looking forward to the update!
